### ISSUE TITLE
Add support for Channels

### ISSUE THREAD

**Issue by jordan2175** [oasis-tcs/cti-taxii2#2] opened 2017-08-30 18:17 UTC
We need to add support for channels (pub/sub) in TAXII.

**Comment by MarkDavidson** [comment] 2017-10-11 17:24
Recommendation: Discuss scope and goals at F2F

**Comment by MarkDavidson** [comment] 2017-10-11 17:25
Dupe of https://github.com/oasis-tcs/cti-taxii2/issues/3

**Closed as completed by MarkDavidson** 2017-10-11 17:25 UTC
Labels: Status: Closed Duplicate
